baseurl = "https://ruszkow.ski"
languageCode = "en-uk"
theme = ["terminal", "reveal-hugo"]
paginate = 5

# Make URLs case insensitive - NEEDS FIXING
# disablePathToLower = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
  avatarurl = "https://avatars1.githubusercontent.com/u/20771863"
  author = "Adam Ruszkowski"

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  weight = 1
  url = "https://github.com/asongtoruin/"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  weight = 2
  url = "https://twitter.com/adam_rusz"

[[params.social]]
  name = "Stack Overflow"
  icon = "fab fa-stack-overflow"
  weight = 3
  url = "https://stackoverflow.com/users/5309300/asongtoruin"

[languages]
  [languages.en]
    languageName = "English"
    title = "ruszkow.ski"
    subtitle = "data, graphs and other nonsense"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ruszkow.ski"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "graphs"
        name = "Graphs"
        url = "/graphs"
        weight = 30
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 40

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[reveal_hugo]
custom_theme = "pvfc-slides.scss"
custom_theme_compile =  true